import {RoutexClient,AccountField} from "https://esm.sh/routex-client@0.6.0?bundle";
const el=id=>document.getElementById(id);let client=new RoutexClient(),selected=null,pending=null,busy=false;
const status=t=>{el("bankBrowserStatus").textContent=t;};
async function apiCall(path,body){return request(path,{method:"POST",body:JSON.stringify(body)});}
function setBusy(v){busy=v;for(const id of ["bankStart","bankConfirm"])el(id).disabled=v;}
const IBAN_LENGTHS={AL:28,AD:24,AT:20,AZ:28,BE:16,BG:22,BA:20,HR:21,CY:28,CZ:24,DK:18,EE:20,FI:18,FR:27,GE:22,DE:22,GI:23,GR:27,HU:28,IS:26,IE:22,IT:27,LV:21,LI:21,LT:20,LU:20,MT:31,MC:27,MD:24,ME:22,NL:18,MK:19,NO:15,PL:28,PT:25,RO:24,SM:27,RS:22,SK:24,SI:19,ES:24,SE:24,CH:21,TR:26,UA:29,GB:22,VA:22};
function normalizeIban(v){const x=String(v||"").replace(/[\\s-]/g,"").toUpperCase();if(!/^[A-Z]{2}[0-9]{2}[A-Z0-9]+$/.test(x)||x.length!==IBAN_LENGTHS[x.slice(0,2)])return null;const rotated=x.slice(4)+x.slice(0,4);let remainder=0;for(const char of rotated){const digits=/[A-Z]/.test(char)?String(char.charCodeAt(0)-55):char;for(const digit of digits)remainder=(remainder*10+Number(digit))%97;}return remainder===1?x:null;}
async function ticket(service="Accounts"){const r=await apiCall("/bank-connect/ticket",{service});return r.ticket;}
function banks(items){el("bankMatches").replaceChildren();const list=Array.isArray(items)?items:items?.connections||[];if(!list.length){status("Geen banken gevonden. Zoek op een andere naam of IBAN.");return;}for(const bank of list){const b=document.createElement("button");b.type="button";b.className="web-button";b.style.margin="6px";b.textContent=bank.displayName||bank.name||bank.id;b.addEventListener("click",()=>{selected=bank;el("bankSelectedName").textContent=b.textContent;el("bankConsent").hidden=false;status("Bank geselecteerd. Start de verbinding om toestemming te geven.");});el("bankMatches").append(b);}}
el("bankSearchForm").addEventListener("submit",async e=>{e.preventDefault();if(busy)return;setBusy(true);try{const q=el("bankSearchInput").value.trim(),compact=q.replace(/[\s-]/g,"").toUpperCase(),looks=/^[A-Z]{2}[0-9]{2}/.test(compact),iban=normalizeIban(q);if(looks&&!iban)throw Error("Ongeldig IBAN. Controleer de landcode, lengte en controlecijfers (NL: 18 tekens, BE: 16 tekens).");status("Banken zoeken…");const found=await client.search({ticket:await ticket(),filters:(iban?[iban]:q.split(/\s+/).filter(Boolean)).map(term=>({term})),ibanDetection:true,limit:50});banks(found);}catch(err){status("Bank zoeken mislukt: "+err.message);}finally{setBusy(false);}});
async function handle(response,issued){const jwt=response?.jwt||response?.result?.jwt||response?.authenticated?.jwt||response?.result?.authenticated?.jwt;if(jwt){await apiCall("/bank-connect/result",{jwt});pending=null;el("bankConfirmation").hidden=true;el("bankPass").value="";status("Bankrekeninggegevens ontvangen en veilig opgeslagen.");await loadBankData();return;}const redirect=response?.redirect||((response?.url||response?.handle)?response:null);const dialog=response?.dialog||response?.input;const context=redirect?.context||response?.redirectHandle?.context||dialog?.input?.context||dialog?.context||dialog?.input?.context||response?.input?.context;let url=redirect?.url;const handle=response?.redirectHandle?.handle||redirect?.handle;if(handle){const r=await client.registerRedirectUri({ticket:issued,handle,redirectUri:location.origin+"/webapp.html#bank"});url=typeof r==="string"?r:r?.url;}if(!context)throw Error("YAXI gaf geen bruikbare bevestigingscontext terug.");pending={ticket:issued,context,dialog:!!dialog,kind:dialog?.input||dialog||response?.input};el("bankConfirmation").hidden=false;el("bankInstructions").textContent=dialog?.message||response?.message||"Bevestig de autorisatie in je bankomgeving en klik daarna op Bankbevestiging controleren.";if(url){const href=String(url);if(!href.startsWith("https://"))throw Error("Ongeldige bankredirect.");window.open(href,"_blank","noopener,noreferrer");status("Bankomgeving geopend. Rond de autorisatie af en keer terug naar dit tabblad.");}else status("Volg de bevestigingsinstructies van je bank.");}
el("bankStart").addEventListener("click",async()=>{if(!selected||busy)return;setBusy(true);try{const issued=await ticket(),credentials={connectionId:selected.id},userId=el("bankUser").value.trim(),password=el("bankPass").value;if(userId)credentials.userId=userId;if(password)credentials.password=password;await client.setRedirectUri(location.origin+"/webapp.html#bank");status("Bankautorisatie wordt gestart…");const r=await client.accounts({ticket:issued,credentials,fields:[AccountField.Iban,AccountField.Currency,AccountField.OwnerName]});el("bankPass").value="";await handle(r,issued);}catch(err){el("bankPass").value="";status("Bankverbinding mislukt: "+err.message);}finally{setBusy(false);}});
el("bankConfirm").addEventListener("click",async()=>{if(!pending||busy)return;setBusy(true);try{const {ticket,context,dialog,kind}=pending;const answer=el("bankAnswer").value.trim(),needsInput=dialog&&(kind?.options||kind?.choices||kind?.type==="field"||kind?.constructor?.name?.match(/Field|Selection/));const r=needsInput?await client.respondAccounts({ticket,context,response:answer}):await client.confirmAccounts({ticket,context});await handle(r,ticket);}catch(err){status("Bevestiging mislukt: "+err.message);}finally{setBusy(false);}});
async function loadBankData(){try{const d=await request("/bank-connect/data");const a=d.accounts||d.latest?.Accounts?.result||[];status("Bankgegevens vernieuwd. "+(Array.isArray(a)?a.length:"")+" rekening(en) gevonden.");}catch(e){status("Bankgegevens niet beschikbaar: "+e.message);}}
