let RoutexClient,AccountField;
try{({RoutexClient,AccountField}=await import("./bank-client.bundle.js"));if(typeof RoutexClient!=="function")throw Error("YAXI-client ontbreekt");}catch(e){const n=document.getElementById("bankBrowserStatus");if(n)n.textContent="YAXI-bankmodule kan niet worden geladen: "+e.message;throw e;}
const el=id=>document.getElementById(id);let client=new RoutexClient(),selected=null,pending=null,busy=false;try{pending=JSON.parse(sessionStorage.getItem("saldoBankPending")||"null");}catch{}
const status=t=>{el("bankBrowserStatus").textContent=t;};
async function apiCall(path,body){return request(path,{method:"POST",body:JSON.stringify(body)});}
function setBusy(v){busy=v;for(const id of ["bankStart","bankConfirm"])el(id).disabled=v;}
const IBAN_LENGTHS={AL:28,AD:24,AT:20,AZ:28,BH:22,BE:16,BG:22,BA:20,BR:29,BY:28,CR:22,HR:21,CY:28,CZ:24,DK:18,DJ:27,DO:28,EE:20,EG:29,SV:28,FO:18,FI:18,FR:27,GE:22,DE:22,GI:23,GR:27,GL:18,GT:28,HU:28,IS:26,IQ:23,IE:22,IL:23,IT:27,JO:30,KZ:20,XK:20,KW:30,LV:21,LB:28,LI:21,LT:20,LU:20,LY:25,MT:31,MR:27,MU:30,MD:24,MC:27,MN:20,ME:22,NL:18,MK:19,NO:15,PK:24,PS:29,PL:28,PT:25,QA:29,RO:24,RU:33,LC:32,SM:27,ST:25,SA:24,RS:22,SC:31,SK:24,SI:19,SO:23,ES:24,SD:18,SE:24,CH:21,TL:23,TN:24,TR:26,UA:29,AE:23,GB:22,VA:22,VG:24};
function compactIban(v){return String(v||"").normalize("NFKC").replace(/[^A-Za-z0-9]/g,"").toUpperCase();}
function formatIban(v){return compactIban(v).replace(/(.{4})/g,"$1 ").trim();}
function normalizeIban(v){const x=compactIban(v);if(!/^[A-Z]{2}[0-9]{2}[A-Z0-9]+$/.test(x)||x.length!==IBAN_LENGTHS[x.slice(0,2)])return null;const rotated=x.slice(4)+x.slice(0,4);let remainder=0;for(const char of rotated){const digits=/[A-Z]/.test(char)?String(char.charCodeAt(0)-55):char;for(const digit of digits)remainder=(remainder*10+Number(digit))%97;}return remainder===1?x:null;}
async function ticket(service="Accounts"){const r=await apiCall("/bank-connect/ticket",{service});return r.ticket;}
let lastSearch="";
function banks(items){
 const matches=el("bankMatches");matches.replaceChildren();selected=null;el("bankConsent").hidden=true;
 const list=Array.isArray(items)?items:Array.isArray(items?.connections)?items.connections:Array.isArray(items?.results)?items.results:[];
 const q=lastSearch.trim().toLowerCase(),isIban=/^[A-Z]{2}[0-9]{2}/i.test(q);
 const aliases=q==="wise"||q==="transferwise"||q==="wise europe sa"?["wise","transferwise"]:q==="abn"||q==="abn amro"?["abn amro"]:q.split(/\s+/).filter(Boolean);
 const normalized=v=>String(v||"").toLowerCase().replace(/[^a-z0-9]/g,"");
 let shown=0;const observed=[];
 for(const bank of list){
  const name=String(bank.displayName||bank.name||"").trim(),id=String(bank.id||bank.connectionId||"");
  if(name)observed.push(name);
  if(!name||!id||isIban)continue;
  const fields=[name,bank.institutionName,bank.bankName,bank.legalName,...(Array.isArray(bank.aliases)?bank.aliases:[])].map(normalized);
  if(!aliases.some(alias=>fields.some(field=>field.includes(normalized(alias)))))continue;
  const b=document.createElement("button");b.type="button";b.className="web-button";b.style.margin="6px";b.textContent=name;
  b.addEventListener("click",()=>{selected=bank;el("bankSelectedName").textContent=name;el("bankConsent").hidden=false;status("Geselecteerd: "+name+". Controleer de officiële bankomgeving vóór autorisatie.");});
  matches.append(b);shown++;
 }
 if(isIban){status("YAXI gaf "+list.length+" resultaat/resultaten voor dit IBAN. Om verkeerde bankautorisatie te voorkomen kun je geen bank op basis van uitsluitend een IBAN selecteren. Zoek op de officiële banknaam.");return;}
 if(shown){status(shown+" passende bank(en) gevonden. Controleer de naam vóór autorisatie.");return;}
 const names=[...new Set(observed)].slice(0,8);
 status("YAXI gaf "+list.length+" resultaat/resultaten; geen bevestigde match voor '"+lastSearch+"'. "+(names.length?"Door YAXI genoemde instellingen (niet selecteerbaar): "+names.join(", ")+". ":"")+"Er is geen veilige bankverbinding beschikbaar via deze zoekopdracht.");
}
el("bankSearchForm").addEventListener("submit",async e=>{e.preventDefault();if(busy)return;setBusy(true);try{const q=el("bankSearchInput").value.trim(),compact=q.replace(/[\s-]/g,"").toUpperCase(),looks=/^[A-Z]{2}[0-9]{2}/.test(compact),iban=normalizeIban(q);if(looks&&!iban)throw Error("Ongeldig IBAN. Controleer de landcode, lengte en controlecijfers (NL: 18 tekens, BE: 16 tekens).");status("Banken zoeken…");const found=await client.search({ticket:await ticket(),filters:(iban?[iban]:q.split(/\s+/).filter(Boolean)).map(term=>({term})),ibanDetection:true,limit:50});lastSearch=iban||q;if(iban)el("bankSearchInput").value=formatIban(iban);banks(found);}catch(err){status("Bank zoeken mislukt: "+err.message);}finally{setBusy(false);}});
async function handle(response,issued){const jwt=response?.jwt||response?.result?.jwt||response?.authenticated?.jwt||response?.result?.authenticated?.jwt;if(jwt){await apiCall("/bank-connect/result",{jwt});pending=null;sessionStorage.removeItem("saldoBankPending");el("bankConfirmation").hidden=true;el("bankPass").value="";status("Bankrekeninggegevens ontvangen en veilig opgeslagen.");await loadBankData();return;}const redirect=response?.redirect||((response?.url||response?.handle)?response:null);const dialog=response?.dialog||response?.input;const context=redirect?.context||response?.redirectHandle?.context||dialog?.input?.context||dialog?.context||dialog?.input?.context||response?.input?.context;let url=redirect?.url;const handle=response?.redirectHandle?.handle||redirect?.handle;if(handle){const r=await client.registerRedirectUri({ticket:issued,handle,redirectUri:location.origin+"/webapp.html#bank"});url=typeof r==="string"?r:r?.url;}if(!context)throw Error("YAXI gaf geen bruikbare bevestigingscontext terug.");pending={ticket:issued,context,dialog:!!dialog,kind:dialog?.input||dialog||response?.input};sessionStorage.setItem("saldoBankPending",JSON.stringify(pending));el("bankConfirmation").hidden=false;el("bankInstructions").textContent=dialog?.message||response?.message||"Bevestig de autorisatie in je bankomgeving en klik daarna op Bankbevestiging controleren.";if(url){const href=String(url);if(!href.startsWith("https://"))throw Error("Ongeldige bankredirect.");const opened=window.open(href,"_blank","noopener,noreferrer");if(!opened){status("Pop-up geblokkeerd. Open de beveiligde bankpagina via de knop hieronder.");const link=document.createElement("a");link.href=href;link.target="_blank";link.rel="noopener noreferrer";link.className="web-button";link.textContent="Open beveiligde bankomgeving";el("bankConfirmation").append(link);}else status("Bankomgeving geopend. Rond de autorisatie af en keer terug naar dit tabblad.");}else status("Volg de bevestigingsinstructies van je bank.");}
el("bankStart").addEventListener("click",async()=>{if(!selected||busy)return;setBusy(true);try{const issued=await ticket(),credentials={connectionId:selected.id||selected.connectionId},userId=el("bankUser").value.trim(),password=el("bankPass").value;if(userId)credentials.userId=userId;if(password)credentials.password=password;await client.setRedirectUri(location.origin+"/webapp.html#bank");status("Bankautorisatie wordt gestart…");const r=await client.accounts({ticket:issued,credentials,fields:[AccountField.Iban,AccountField.Currency,AccountField.OwnerName]});el("bankPass").value="";await handle(r,issued);}catch(err){el("bankPass").value="";status("Bankverbinding mislukt: "+err.message);}finally{setBusy(false);}});
el("bankConfirm").addEventListener("click",async()=>{if(!pending||busy)return;setBusy(true);try{const {ticket,context,dialog,kind}=pending;const answer=el("bankAnswer").value.trim(),needsInput=dialog&&(kind?.options||kind?.choices||kind?.type==="field"||kind?.constructor?.name?.match(/Field|Selection/));const r=needsInput?await client.respondAccounts({ticket,context,response:answer}):await client.confirmAccounts({ticket,context});await handle(r,ticket);}catch(err){status("Bevestiging mislukt: "+err.message);}finally{setBusy(false);}});
async function loadBankData(){try{const d=await request("/bank-connect/data");const a=d.accounts||d.latest?.Accounts?.result||[];status("Bankgegevens vernieuwd. "+(Array.isArray(a)?a.length:"")+" rekening(en) gevonden.");}catch(e){status("Bankgegevens niet beschikbaar: "+e.message);}}

if(pending){el("bankConfirmation").hidden=false;status("Bankautorisatie hervat. Rond de bevestiging af via je bank en klik op Bankbevestiging controleren.");}
