import React,{useEffect,useState} from 'react';
import {View,Text,TextInput,Pressable,ScrollView,ActivityIndicator,Linking,StyleSheet} from 'react-native';
import * as SecureStore from 'expo-secure-store';
import {StatusBar} from 'expo-status-bar';
import api from './src/api';
const BLUE='#173c60',GREEN='#2d805f';
const intro=[['Welkom bij Saldo Slim','Krijg inzicht in je geld en houd grip op je dagelijkse budget.'],['Bereken je bestedingsruimte','Vul je inkomsten, vaste lasten en reserve in en zie wat je per dag kunt besteden.'],['Jouw mogelijkheden','Bekijk je abonnement, vraag hulp aan en beheer als eigenaar je gebruikers.']];
function Btn({title,onPress,secondary=false}){return <Pressable onPress={onPress} style={[styles.button,secondary&&{backgroundColor:BLUE}]}><Text style={styles.buttonText}>{title}</Text></Pressable>}
function Field({label,value,onChangeText,secureTextEntry=false,keyboardType='default'}){return <View style={{marginBottom:12}}><Text style={styles.label}>{label}</Text><TextInput style={styles.input} value={value} onChangeText={onChangeText} secureTextEntry={secureTextEntry} keyboardType={keyboardType} autoCapitalize={keyboardType==='email-address'?'none':'sentences'}/></View>}
function Card({title,children}){return <View style={styles.card}><Text style={styles.heading}>{title}</Text>{children}</View>}
export default function App(){
 const [stage,setStage]=useState('loading'),[slide,setSlide]=useState(0),[mode,setMode]=useState('login'),[tab,setTab]=useState('overzicht');
 const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[firstName,setFirstName]=useState(''),[lastName,setLastName]=useState(''),[age,setAge]=useState(''),[phone,setPhone]=useState('');
 const [token,setToken]=useState(''),[me,setMe]=useState(null),[ent,setEnt]=useState(null),[budget,setBudget]=useState({income:'',fixed_expenses:'',reservations:'',days_remaining:'30'}),[admin,setAdmin]=useState({}),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[subject,setSubject]=useState(''),[message,setMessage]=useState('');
 const role=String(me?.role||'').toLowerCase(),privileged=['owner','moderator'].includes(role),owner=role==='owner';
 const n=v=>Number(String(v||'0').replace(',','.'))||0;
 const daily=(n(budget.income)-n(budget.fixed_expenses)-n(budget.reservations))/Math.max(1,n(budget.days_remaining));
 const fail=e=>setNotice(e?.message||'Er is iets misgegaan.');
 async function loadProfile(){const [p,e,b]=await Promise.all([api.getMe(),api.getEntitlements(),api.getBudgetProfile()]);setMe(p.user||p);setEnt(e);const q=b.profile||b.budget||b;setBudget({income:String(q.income??''),fixed_expenses:String(q.fixed_expenses??q.fixedExpenses??''),reservations:String(q.reservations??''),days_remaining:String(q.days_remaining??q.daysRemaining??30)});}
 useEffect(()=>{(async()=>{try{const t=await SecureStore.getItemAsync('saldoSlimToken');const seen=await SecureStore.getItemAsync('saldoSlimIntro');if(t){api.setToken(t);setToken(t);await loadProfile();setStage('app')}else setStage(seen?'auth':'intro')}catch(e){setStage('auth')}})()},[]);
 async function authenticate(){setBusy(true);setNotice('');try{const response=mode==='register'?await api.register({firstName,lastName,age:Number(age),phone,email,password}):await api.login({email,password});if(mode==='register'&&!response.token){setMode('login');setNotice('Registratie gelukt. Log nu in.');return}const t=response.token;if(!t)throw Error('Log opnieuw in.');await SecureStore.setItemAsync('saldoSlimToken',t);api.setToken(t);setToken(t);await loadProfile();setStage('app')}catch(e){fail(e)}finally{setBusy(false)}}
 async function logout(){await SecureStore.deleteItemAsync('saldoSlimToken');api.setToken(null);setToken('');setMe(null);setStage('auth');setTab('overzicht')}
 async function saveBudget(){setBusy(true);setNotice('');try{await api.updateBudgetProfile({income:n(budget.income),fixed_expenses:n(budget.fixed_expenses),reservations:n(budget.reservations),days_remaining:Math.max(1,n(budget.days_remaining))});setNotice('Je financiële profiel is opgeslagen.')}catch(e){fail(e)}finally{setBusy(false)}}
 async function loadAdmin(){setBusy(true);setNotice('');try{const [overview,users,subscriptions,payouts,support,audit]=await Promise.all([api.getAdminOverview(),api.getAdminUsers(),api.getAdminSubscriptions(),api.getAdminPayouts(),api.getAdminSupport(),owner?api.getAdminAudit():Promise.resolve({audit:[]})]);setAdmin({overview,users:users.users||[],subscriptions:subscriptions.subscriptions||[],payouts:payouts.payouts||[],support:support.tickets||[],audit:audit.audit||[]})}catch(e){fail(e)}finally{setBusy(false)}}
 async function changeRole(id,role){try{await api.setAdminUserRole(id,{role});await loadAdmin()}catch(e){fail(e)}}
 async function changeStatus(id,status){try{await api.setAdminUserStatus(id,{status});await loadAdmin()}catch(e){fail(e)}}
 async function sendSupport(){setBusy(true);try{await api.sendSupport({subject,message});setSubject('');setMessage('');setNotice('Je bericht is verzonden.')}catch(e){fail(e)}finally{setBusy(false)}}
 if(stage==='loading')return <View style={styles.center}><ActivityIndicator size='large' color={GREEN}/><Text>Saldo Slim wordt gestart…</Text></View>;
 if(stage==='intro')return <View style={styles.page}><Text style={styles.logo}>Saldo Slim</Text><Card title={intro[slide][0]}><Text style={styles.body}>{intro[slide][1]}</Text><Text style={styles.muted}>Stap {slide+1} van {intro.length}</Text></Card><Btn title={slide===intro.length-1?'Aan de slag':'Volgende'} onPress={async()=>{if(slide<intro.length-1)setSlide(slide+1);else{await SecureStore.setItemAsync('saldoSlimIntro','1');setStage('auth')}}}/><Btn secondary title='Overslaan' onPress={()=>setStage('auth')}/></View>;
 if(stage==='auth')return <ScrollView contentContainerStyle={styles.page}><Text style={styles.logo}>Saldo Slim</Text><Text style={styles.body}>Jouw financiële overzicht</Text><View style={styles.tabs}><Btn title='Inloggen' onPress={()=>setMode('login')}/><Btn title='Registreren' secondary onPress={()=>setMode('register')}/></View><Card title={mode==='login'?'Inloggen':'Registreren'}>{mode==='register'&&<><Field label='Voornaam' value={firstName} onChangeText={setFirstName}/><Field label='Achternaam' value={lastName} onChangeText={setLastName}/><Field label='Leeftijd' value={age} onChangeText={setAge} keyboardType='numeric'/><Field label='Telefoonnummer' value={phone} onChangeText={setPhone} keyboardType='phone-pad'/></>}<Field label='E-mailadres' value={email} onChangeText={setEmail} keyboardType='email-address'/><Field label='Wachtwoord' value={password} onChangeText={setPassword} secureTextEntry/><Btn title={busy?'Even wachten…':mode==='login'?'Inloggen':'Account aanmaken'} onPress={authenticate}/></Card>{!!notice&&<Text style={styles.notice}>{notice}</Text>}</ScrollView>;
 return <ScrollView contentContainerStyle={styles.page}><StatusBar style='dark'/><Text style={styles.logo}>Saldo Slim</Text><Text style={styles.body}>Welkom, {me?.firstName||me?.name||'gebruiker'}</Text><Text style={styles.muted}>{privileged?'Lifetime Premium (gratis)':ent?.effectivePlan||me?.plan||'Basis'}</Text><View style={styles.tabs}>{['overzicht','support',...(privileged?['admin']:[])].map(x=><Pressable key={x} onPress={()=>{setTab(x);setNotice('');if(x==='admin')loadAdmin()}}><Text style={[styles.nav,tab===x&&{color:GREEN}]}>{x==='overzicht'?'Overzicht':x==='support'?'Support':'Admin'}</Text></Pressable>)}</View>{!!notice&&<Text style={styles.notice}>{notice}</Text>}
 {tab==='overzicht'&&<><Card title='Veilig te besteden per dag'><Text style={styles.amount}>€ {daily.toFixed(2).replace('.',',')}</Text><Text style={styles.muted}>Op basis van inkomsten, vaste lasten, reserve en periode.</Text></Card><Card title='Financieel profiel'>{[['Inkomen per periode (€)','income'],['Vaste lasten (€)','fixed_expenses'],['Reserve (€)','reservations'],['Aantal dagen','days_remaining']].map(([label,key])=><Field key={key} label={label} value={budget[key]} keyboardType='decimal-pad' onChangeText={v=>setBudget({...budget,[key]:v})}/>)}<Btn title='Profiel opslaan' onPress={saveBudget}/></Card><Card title='Abonnement'><Text style={styles.body}>{privileged?'Alle functies zijn gratis vrijgeschakeld.':ent?.effectivePlan||me?.plan||'Basis'}</Text><Btn secondary title='Bekijk abonnementen' onPress={()=>Linking.openURL('https://partydj-dylan.nl/account.html')}/></Card></>}
 {tab==='support'&&<Card title='Contact met ondersteuning'><Field label='Onderwerp' value={subject} onChangeText={setSubject}/><Field label='Bericht' value={message} onChangeText={setMessage}/><Btn title='Verstuur bericht' onPress={sendSupport}/></Card>}
 {tab==='admin'&&privileged&&<><Card title='Beheer'><Text style={styles.body}>Rol: {owner?'Eigenaar':'Moderator'}</Text><Btn title='Vernieuw gegevens' onPress={loadAdmin}/></Card><Card title='Dashboard'><Text>Gebruikers: {admin.overview?.totalUsers??'—'}</Text><Text>Abonnementen: {admin.overview?.totalSubscriptions??'—'}</Text></Card><Card title='Gebruikers'>{(admin.users||[]).map(u=><View key={u.id} style={styles.entry}><Text>{u.name} — {u.email}</Text><Text>{u.role} · {u.status}</Text>{owner&&u.role!=='owner'&&<><Btn title={u.role==='moderator'?'Maak gebruiker':'Maak moderator'} onPress={()=>changeRole(u.id,u.role==='moderator'?'user':'moderator')}/><Btn secondary title={u.status==='active'?'Deactiveer':'Activeer'} onPress={()=>changeStatus(u.id,u.status==='active'?'disabled':'active')}/></>}</View>)}</Card><Card title='Abonnementen'><Text>{(admin.subscriptions||[]).length} abonnementen</Text></Card><Card title='Uitbetalingen'><Text>{(admin.payouts||[]).length} uitbetalingen</Text></Card><Card title='Supporttickets'><Text>{(admin.support||[]).length} tickets</Text></Card>{owner&&<Card title='Auditlog'><Text>{(admin.audit||[]).length} regels</Text></Card>}</>}
 <Btn secondary title='Uitloggen' onPress={logout}/></ScrollView>
}
const styles=StyleSheet.create({page:{padding:22,paddingTop:55,backgroundColor:'#f3f6f8',flexGrow:1},center:{flex:1,justifyContent:'center',alignItems:'center'},logo:{fontSize:34,fontWeight:'800',color:BLUE,marginBottom:12},heading:{fontSize:23,fontWeight:'700',color:BLUE,marginBottom:18},body:{fontSize:17,color:BLUE,marginBottom:15},muted:{fontSize:15,color:'#657789',marginTop:8},card:{backgroundColor:'#fff',padding:20,borderRadius:18,marginVertical:12,borderWidth:1,borderColor:'#d8e0e5'},label:{fontSize:16,fontWeight:'600',color:BLUE,marginBottom:8},input:{borderWidth:1,borderColor:'#cdd7de',borderRadius:10,padding:12,fontSize:17,color:BLUE},button:{backgroundColor:GREEN,padding:14,borderRadius:10,alignItems:'center',marginVertical:7},buttonText:{color:'#fff',fontSize:16,fontWeight:'700'},tabs:{flexDirection:'row',justifyContent:'space-around',gap:8,marginVertical:15,flexWrap:'wrap'},nav:{fontSize:18,fontWeight:'700',color:BLUE},amount:{fontSize:40,color:GREEN,fontWeight:'800'},notice:{padding:14,backgroundColor:'#fff1c9',borderRadius:10,color:BLUE,marginVertical:10},entry:{paddingVertical:12,borderBottomWidth:1,borderColor:'#e0e6eb'}});
