import api from './api';
import React,{useEffect,useMemo,useState} from 'react';
import {View,Text,TextInput,Pressable,ScrollView} from 'react-native';
import * as SecureStore from 'expo-secure-store';
const categories=['Boodschappen','Huur/Hypotheek','Vaste lasten','Vervoer','Leuke dingen','Zorg','Winkelen','Overig'];
const green='#2d805f',blue='#173c60';
const money=v=>'€ '+(Number(v)||0).toFixed(2).replace('.',',');
const amount=t=>{const a=t?.amount;const n=Number(typeof a==='object'?a?.amount:a??t?.value??0);return Number.isFinite(n)?n:0};
const dateOf=t=>String(t?.bookingDate||t?.date||t?.valueDate||'').slice(0,10);
const nameOf=t=>String(t?.creditor?.name||t?.debtor?.name||t?.merchantName||t?.description||t?.remittanceInformationUnstructured||'Transactie');
const classify=t=>{const s=nameOf(t).toLowerCase();if(/albert heijn|jumbo|lidl|aldi|plus supermarkt|dirk|supermarkt|picnic/.test(s))return 'Boodschappen';if(/huur|hypotheek|woningcorporatie/.test(s))return 'Huur/Hypotheek';if(/netflix|spotify|disney|videoland|ziggo|vodafone|kpn|energie|waterbedrijf|verzekering/.test(s))return 'Vaste lasten';if(/ns |ov-chip|arriva|shell|esso|tankstation|q-park/.test(s))return 'Vervoer';if(/bioscoop|restaurant|cafe|cinema|pathe/.test(s))return 'Leuke dingen';return 'Overig'};
const card={padding:14,borderWidth:1,borderColor:'#d8e0e5',borderRadius:12,marginVertical:8,backgroundColor:'#fff'};
const label={fontSize:16,color:blue,fontWeight:'700',marginVertical:7};
const input={borderWidth:1,borderColor:'#cdd7de',borderRadius:9,padding:10,color:blue,fontSize:16,marginVertical:5};
function Action({title,onPress}){return <Pressable onPress={onPress} style={{backgroundColor:green,padding:11,borderRadius:9,marginVertical:6}}><Text style={{color:'#fff',textAlign:'center',fontWeight:'700'}}>{title}</Text></Pressable>}
function Bar({value,total}){const p=total>0?Math.max(0,Math.min(100,value/total*100)):0;return <View style={{height:12,backgroundColor:'#e6ebef',borderRadius:9,overflow:'hidden',marginVertical:6}}><View style={{width:p+'%',height:12,backgroundColor:p>=100?'#bf3b3b':p>=80?'#e4a12a':green}}/></View>}
export default function FinanceTools({bankData,userKey,access={},onUpgrade=()=>{}}){
 const can=k=>Boolean(access.all||access[k]);
 const limitGoals=access.all?Infinity:(access.maxGoals??0);
 const limitBills=access.all?Infinity:(access.maxBills??1);
 const limitBudgets=access.all?Infinity:(access.maxBudgets??0);
 const key='saldoFinance_'+String(userKey||'guest').replace(/[^a-zA-Z0-9_-]/g,'_').slice(0,100);
 const [data,setData]=useState({categories:{},splits:{},budgets:[],bills:[],goals:[],period:'month',payday:'1'});
 const [ready,setReady]=useState(false),[tab,setTab]=useState('transacties'),[notice,setNotice]=useState('');
 const [selected,setSelected]=useState(''),[cat,setCat]=useState('Boodschappen'),[splitAmount,setSplitAmount]=useState(''),[splitCat,setSplitCat]=useState('Leuke dingen');
 const [budgetCat,setBudgetCat]=useState('Boodschappen'),[budgetLimit,setBudgetLimit]=useState(''),[period,setPeriod]=useState('month');
 const [billName,setBillName]=useState(''),[billAmount,setBillAmount]=useState(''),[billDay,setBillDay]=useState('1');
 const [goalName,setGoalName]=useState(''),[goalTarget,setGoalTarget]=useState(''),[goalDeposit,setGoalDeposit]=useState('');
 useEffect(()=>{let alive=true;setReady(false);SecureStore.getItemAsync(key).then(raw=>{if(alive){let saved={};try{saved=raw?JSON.parse(raw):{}}catch(_){}setData({categories:{},splits:{},budgets:[],bills:[],goals:[],period:'month',payday:'1',...saved});setReady(true)}}).catch(()=>{if(alive)setReady(true)});return()=>{alive=false}},[key]);
 const save=next=>{setData(next);SecureStore.setItemAsync(key,JSON.stringify(next)).catch(()=>setNotice('Opslaan op dit apparaat is mislukt.'))};
 const consume=async(feature)=>{try{await api.consumeFeature(feature);return true}catch(e){setNotice(e?.data?.error==='feature_limit_reached'?'Je maandlimiet voor deze functie is bereikt. Upgrade je abonnement.':'De limietcontrole is niet beschikbaar. Probeer het later opnieuw.');return false}};
 const transactions=useMemo(()=>Array.isArray(bankData?.transactions)?bankData.transactions:[],[bankData]);
 const items=useMemo(()=>transactions.map((t,i)=>({t,id:String(t.id||t.transactionId||[dateOf(t),nameOf(t),amount(t),i].join('|')),value:amount(t),date:dateOf(t),name:nameOf(t)})),[transactions]);
 const now=new Date();const today=now.toISOString().slice(0,10);const [yy,mm]=today.split('-').map(Number);
 const start=period==='week'?(()=>{const d=new Date(now);d.setDate(d.getDate()-(d.getDay()+6)%7);return d.toISOString().slice(0,10)})():period==='pay'?(()=>{const d=Math.max(1,Math.min(28,Number(data.payday)||1));return (now.getDate()>=d?new Date(yy,mm-1,d):new Date(yy,mm-2,d)).toISOString().slice(0,10)})():new Date(yy,mm-1,1).toISOString().slice(0,10);
 const current=items.filter(x=>x.date>=start&&x.date<=today);
 const expenses=current.filter(x=>x.value<0);
 const income=current.filter(x=>x.value>0).reduce((s,x)=>s+x.value,0);
 const totalExpense=expenses.reduce((s,x)=>s+Math.abs(x.value),0);
 const pieces=x=>{const parts=data.splits[x.id];return Array.isArray(parts)&&parts.length?parts:[{category:data.categories[x.id]||(can('autoCategories')?classify(x.t):'Overig'),amount:Math.abs(x.value)}]};
 const spent=catName=>expenses.reduce((s,x)=>s+pieces(x).filter(p=>p.category===catName).reduce((a,p)=>a+Number(p.amount||0),0),0);
 const recurring=useMemo(()=>{const groups={};items.filter(x=>x.value<0).forEach(x=>{const k=x.name.toLowerCase().trim();(groups[k]||(groups[k]=[])).push(x)});return Object.values(groups).filter(a=>a.length>=2&&new Set(a.map(x=>x.date.slice(0,7))).size>=2).filter(a=>{const v=a.map(x=>Math.abs(x.value));return Math.max(...v)-Math.min(...v)<=Math.max(2,v[0]*.15)}).map(a=>({name:a[0].name,value:Math.abs(a[0].value),count:a.length})).slice(0,30)},[items]);
 const months=Array.from({length:6},(_,i)=>{const d=new Date(yy,mm-1-(5-i),1);const m=d.toISOString().slice(0,7);return {name:m,spent:items.filter(x=>x.date.startsWith(m)&&x.value<0).reduce((s,x)=>s+Math.abs(x.value),0)}});
 const selectedItem=items.find(x=>x.id===selected);
 if(!ready)return <Text style={label}>Financiële gegevens laden…</Text>;
 return <View style={card}><Text style={{fontSize:23,fontWeight:'800',color:blue}}>Mijn financiën</Text><Text style={{color:'#657789',marginVertical:7}}>Categorieën, budgetten en spaardoelen worden privé op dit apparaat opgeslagen. Banktransacties komen via YAXI.</Text><View style={{flexDirection:'row',flexWrap:'wrap',gap:7,marginVertical:8}}>{[['transacties','Transacties'],['budget','Budgetten'],['vast','Vaste lasten'],['rapport','Rapportages'],['sparen','Spaarpotjes']].map(([id,t])=><Pressable key={id} onPress={()=>setTab(id)} style={{padding:9,backgroundColor:tab===id?green:'#e6ebef',borderRadius:8}}><Text style={{color:tab===id?'white':blue,fontWeight:'700'}}>{t}</Text></Pressable>)}</View>{!!notice&&<Text style={{color:'#a35d00'}}>{notice}</Text>}
 {!access.all&&<Action title='Bekijk upgrades en extra functies' onPress={onUpgrade}/>}
 {tab==='transacties'&&!can('categories')&&<Text style={label}>Transactiecategorieën zijn beschikbaar vanaf Plus. Upgrade via je account.</Text>}
 {tab==='transacties'&&can('categories')&&<><Text style={label}>Transacties categoriseren en splitsen</Text>{items.length===0&&<Text>Er zijn nog geen banktransacties beschikbaar.</Text>}{items.slice(0,100).map(x=><Pressable key={x.id} onPress={()=>{setSelected(x.id);setCat(data.categories[x.id]||(can('autoCategories')?classify(x.t):'Overig'));setSplitAmount('')}} style={{padding:10,borderBottomWidth:1,borderColor:'#eee'}}><Text style={{color:blue,fontWeight:'600'}}>{x.date} · {x.name}</Text><Text>{money(x.value)} · {pieces(x).map(p=>p.category).join(' + ')}</Text></Pressable>)}{selectedItem&&<View style={card}><Text style={label}>Bewerk: {selectedItem.name} ({money(selectedItem.value)})</Text><ScrollView horizontal>{categories.map(c=><Pressable key={c} onPress={()=>setCat(c)} style={{padding:8,backgroundColor:cat===c?green:'#e6ebef',marginRight:5,borderRadius:6}}><Text style={{color:cat===c?'white':blue}}>{c}</Text></Pressable>)}</ScrollView><Action title='Categorie opslaan' onPress={()=>{save({...data,categories:{...data.categories,[selected]:cat},splits:{...data.splits,[selected]:[]}});setNotice('Categorie opgeslagen.')}}/>{selectedItem.value<0&&can('split')&&<><Text style={label}>Splits bedrag naar twee categorieën</Text><TextInput style={input} value={splitAmount} onChangeText={setSplitAmount} keyboardType='decimal-pad' placeholder='Bedrag eerste deel (€)'/><ScrollView horizontal>{categories.map(c=><Pressable key={c} onPress={()=>setSplitCat(c)} style={{padding:7,marginRight:5,backgroundColor:splitCat===c?green:'#e6ebef',borderRadius:6}}><Text style={{color:splitCat===c?'white':blue}}>{c}</Text></Pressable>)}</ScrollView><Text>Overige bedrag valt onder: {cat}</Text><Action title='Splitsing opslaan' onPress={async()=>{const v=Number(splitAmount.replace(',','.'));const total=Math.abs(selectedItem.value);if(!(v>0&&v<total)){setNotice('Vul een bedrag in tussen € 0 en het totaal.');return}if(!Array.isArray(data.splits[selected])||!data.splits[selected].length){if(!(await consume('transactionSplits')))return;}save({...data,splits:{...data.splits,[selected]:[{category:splitCat,amount:v},{category:cat,amount:Math.round((total-v)*100)/100}]}});setNotice('Splitsing opgeslagen.')}}/></>}</View>}</>}
 {tab==='budget'&&!can('budget')&&<Text style={label}>Budgetten zijn beschikbaar vanaf Plus.</Text>}
 {tab==='budget'&&can('budget')&&<><Text style={label}>Budgetlimieten</Text><View style={{flexDirection:'row',flexWrap:'wrap'}}>{[['week','Week'],['month','Maand'],['pay','Salarisperiode']].map(([v,t])=><Pressable key={v} onPress={()=>{if(v!=='month'&&!can('flexPeriods')){setNotice('Week- en salarisperiodes zijn beschikbaar vanaf Pro.');return}setPeriod(v)}} style={{padding:10,backgroundColor:period===v?green:'#e6ebef',margin:3,borderRadius:7}}><Text style={{color:period===v?'white':blue}}>{t}</Text></Pressable>)}</View>{period==='pay'&&<><Text>Dag waarop je salarisperiode begint (1–28)</Text><TextInput style={input} value={String(data.payday||'1')} onChangeText={v=>save({...data,payday:v.replace(/[^0-9]/g,'').slice(0,2)})} keyboardType='number-pad'/></>}<Text>Uitgaven sinds {start}: {money(totalExpense)}</Text>{data.budgets.filter(b=>b.period===period).map((b,i)=><View key={i} style={card}><Text style={label}>{b.category}: {money(spent(b.category))} / {money(b.limit)}</Text><Bar value={spent(b.category)} total={b.limit}/><Text>{b.limit>0?Math.round(spent(b.category)/b.limit*100):0}% gebruikt</Text><Action title='Verwijder budget' onPress={()=>save({...data,budgets:data.budgets.filter(x=>x!==b)})}/></View>)}<Text style={label}>Nieuw budget</Text><ScrollView horizontal>{categories.map(c=><Pressable key={c} onPress={()=>setBudgetCat(c)} style={{padding:8,backgroundColor:budgetCat===c?green:'#e6ebef',marginRight:5,borderRadius:7}}><Text style={{color:budgetCat===c?'white':blue}}>{c}</Text></Pressable>)}</ScrollView><TextInput style={input} value={budgetLimit} onChangeText={setBudgetLimit} placeholder='Limiet in euro' keyboardType='decimal-pad'/><Action title='Budget opslaan' onPress={()=>{const limit=Number(budgetLimit.replace(',','.'));if(!(limit>0)){setNotice('Vul een geldige limiet in.');return}if(data.budgets.filter(b=>b.period===period&&b.category!==budgetCat).length>=limitBudgets){setNotice('Je abonnement staat maximaal '+limitBudgets+' budgetten toe. Upgrade voor meer.');return}save({...data,budgets:[...data.budgets.filter(b=>!(b.category===budgetCat&&b.period===period)),{category:budgetCat,period,limit}]});setBudgetLimit('')}}/></>}
 {tab==='vast'&&!can('bills')&&<Text style={label}>Vaste lasten bijhouden is beschikbaar vanaf Plus.</Text>}
 {tab==='vast'&&can('bills')&&<><Text style={label}>Mogelijke terugkerende betalingen</Text><Text>Automatisch voorgesteld op basis van meerdere vergelijkbare afschrijvingen in verschillende maanden. Controleer deze zelf.</Text>{can('recurring')&&recurring.length===0&&<Text>Nog geen terugkerende betalingen herkend.</Text>}{!can('recurring')&&<Text>Automatische abonnementenherkenning is beschikbaar vanaf Pro.</Text>}{can('recurring')&&recurring.map((x,i)=><View key={i} style={card}><Text>{x.name}: circa {money(x.value)} · {x.count} keer gezien</Text><Action title='Toevoegen aan kalender' onPress={()=>{if(data.bills.length>=limitBills){setNotice('Je abonnement staat maximaal '+limitBills+' vaste lasten toe.');return}save({...data,bills:[...data.bills,{id:String(Date.now())+i,name:x.name,amount:x.value,day:1}]})}}/></View>)}<Text style={label}>Incassokalender (dag van de maand)</Text>{data.bills.slice().sort((a,b)=>a.day-b.day).map(b=><View key={b.id} style={card}><Text>Dag {b.day}: {b.name} — {money(b.amount)}</Text><Action title='Verwijderen' onPress={()=>save({...data,bills:data.bills.filter(x=>x.id!==b.id)})}/></View>)}<TextInput style={input} placeholder='Naam (bijv. Huur)' value={billName} onChangeText={setBillName}/><TextInput style={input} placeholder='Bedrag (€)' value={billAmount} onChangeText={setBillAmount} keyboardType='decimal-pad'/><TextInput style={input} placeholder='Dag van de maand (1-31)' value={billDay} onChangeText={setBillDay} keyboardType='number-pad'/><Action title='Incasso toevoegen' onPress={()=>{const v=Number(billAmount.replace(',','.')),day=Number(billDay);if(!billName.trim()||!(v>0)||!(day>=1&&day<=31)){setNotice('Vul naam, positief bedrag en dag 1–31 in.');return}if(data.bills.length>=limitBills){setNotice('Je abonnement staat maximaal '+limitBills+' vaste lasten toe.');return}save({...data,bills:[...data.bills,{id:String(Date.now()),name:billName.trim(),amount:v,day}]});setBillName('');setBillAmount('')}}/></>}
 {tab==='rapport'&&!can('reports')&&<Text style={label}>Rapportages zijn beschikbaar vanaf Plus.</Text>}
 {tab==='rapport'&&can('reports')&&<><Text style={label}>Inkomsten versus uitgaven ({period==='week'?'week':period==='pay'?'salarisperiode':'maand'})</Text><Text>Inkomsten: {money(income)} · Uitgaven: {money(totalExpense)}</Text><Bar value={totalExpense} total={Math.max(income,totalExpense,1)}/><Text style={label}>Uitgaven per categorie</Text>{categories.filter(c=>spent(c)>0).map(c=><View key={c}><Text>{c}: {money(spent(c))}</Text><Bar value={spent(c)} total={totalExpense}/></View>)}{can('trend')&&<><Text style={label}>Uitgaventrend afgelopen 6 maanden</Text>{months.map(m=><View key={m.name}><Text>{m.name}: {money(m.spent)}</Text><Bar value={m.spent} total={Math.max(1,...months.map(x=>x.spent))}/></View>)}</>}</>}
 {tab==='sparen'&&!can('goals')&&<Text style={label}>Spaarpotjes zijn beschikbaar vanaf Plus.</Text>}
 {tab==='sparen'&&can('goals')&&<><Text style={label}>Digitale spaarpotjes</Text>{data.goals.map(g=><View key={g.id} style={card}><Text style={label}>{g.name}: {money(g.saved)} / {money(g.target)}</Text><Bar value={g.saved} total={g.target}/><Text>{Math.round(g.saved/g.target*100)}% gespaard</Text><TextInput style={input} placeholder='Bijstorten (€)' value={goalDeposit} onChangeText={setGoalDeposit} keyboardType='decimal-pad'/><Action title='Bedrag toevoegen' onPress={()=>{const v=Number(goalDeposit.replace(',','.'));if(!(v>0)){setNotice('Vul een positief bedrag in.');return}save({...data,goals:data.goals.map(x=>x.id===g.id?{...x,saved:Math.round((x.saved+v)*100)/100}:x)});setGoalDeposit('')}}/><Action title='Spaarpot verwijderen' onPress={()=>save({...data,goals:data.goals.filter(x=>x.id!==g.id)})}/></View>)}<TextInput style={input} placeholder='Doel (bijv. Vakantie)' value={goalName} onChangeText={setGoalName}/><TextInput style={input} placeholder='Doelbedrag (€)' value={goalTarget} onChangeText={setGoalTarget} keyboardType='decimal-pad'/><Action title='Nieuw spaarpotje maken' onPress={()=>{const target=Number(goalTarget.replace(',','.'));if(!goalName.trim()||!(target>0)){setNotice('Vul een naam en positief doelbedrag in.');return}if(data.goals.length>=limitGoals){setNotice('Je abonnement staat maximaal '+limitGoals+' spaarpotjes toe. Upgrade voor meer.');return}save({...data,goals:[...data.goals,{id:String(Date.now()),name:goalName.trim(),target,saved:0}]});setGoalName('');setGoalTarget('')}}/></>}
 </View>
}
